language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - mysql

before_install
  - mysql -u root --password="" < test/resources/data.sql

script: "./gradlew clean build"
