language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

env:
  global:
    - NODE_ENV=production

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"
