language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - docker build -t kimseonggyu1/devbie:latest