spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;
logging:
  config: classpath:log4j2.yml
cloud:
  aws:
    s3:
      bucket: underdong-devbie-images
    region:
      static: ap-northeast-2
      stack:
        auto: false
