spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
cloud:
  aws:
    s3:
      bucket: underdong-devbie-images
    region:
      static: ap-northeast-2
      stack:
        auto: false
