spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

cloud:
  aws:
    s3:
      bucket: underdong-devbie-images
    region:
      static: ap-northeast-2
      stack:
        auto: false
